In [2]:
import pandas as pd 
import numpy as np 
from sklearn.datasets import load_digits
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression

In [3]:
dir(load_digits)

['__annotations__',
 '__builtins__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__getstate__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__type_params__',
 '__wrapped__',
 '_skl_parameter_constraints']

In [14]:
digit=load_digits()

In [16]:
df=pd.DataFrame(digit.data)
df.head()


0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [21]:
digit.target

array([0, 1, 2, ..., 8, 9, 8])

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digit.data,digit.target,test_size=0.2)

In [24]:
model=LinearRegression()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.5814290916938671

In [26]:
model=SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9861111111111112

In [27]:
model=RandomForestClassifier()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.975

In [29]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [31]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9861111111111112

In [33]:
#cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel='linear'),digit.data,digit.target)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [39]:
cross_val_score(RandomForestClassifier(),digit.data,digit.target)

array([0.92777778, 0.90277778, 0.95821727, 0.96935933, 0.91922006])

In [40]:
cross_val_score(LinearRegression(),digit.data,digit.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators=30),digit.data,digit.target)

array([0.92777778, 0.88055556, 0.95264624, 0.95821727, 0.91364903])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=60),digit.data,digit.target)

array([0.92777778, 0.9       , 0.96657382, 0.97493036, 0.93871866])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=90),digit.data,digit.target)

array([0.93055556, 0.90555556, 0.95543175, 0.9637883 , 0.92200557])