In [45]:
import pandas as pd
from sklearn import svm
from sklearn.datasets import load_iris
import numpy as np

In [24]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [25]:
df['target']=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [26]:
df['target_flowers']=df['target'].apply(lambda x: iris.target_names[x])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_flowers  
0         0         setosa  
1         0         setosa  
2         0         setosa  
3         0         setosa  
4         0         setosa  
..      ...            ...  
145       2      virginica  
146       2      virginica  
147       2      virginica  
148       2      virginica  
149       2      virginica  

[150 rows x 6 columns]

In [58]:
from sklearn.model_selection import train_test_split 
X_trian, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [32]:
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_trian,y_train)
model.score(X_test,y_test)
#ots change the score according to given data so its approch is not that use ful

0.9333333333333333

In [33]:
from  sklearn.model_selection import cross_val_score

In [36]:
cross_val_score(svm.SVC(kernel='linear',C=30,gamma='auto'),iris.data,iris.target,cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [40]:
cross_val_score(svm.SVC(kernel='rbf',C=30,gamma='auto'),iris.data,iris.target,cv=5)


array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [41]:
cross_val_score(svm.SVC(kernel='rbf',C=50,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

In [48]:
kernel=['linear','rbf']
C=[10,20,50]
avg_score={}
for kval in kernel:
    for cval in C:
        C_score=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval+'-'+str(cval)]=np.average(C_score)
avg_score        
        

{'linear-10': 0.9733333333333334,
 'linear-20': 0.9666666666666666,
 'linear-50': 0.9666666666666666,
 'rbf-10': 0.9800000000000001,
 'rbf-20': 0.9666666666666668,
 'rbf-50': 0.96}

In [63]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'kernel':['linear','rbf'],
    'C':[1,20,50]
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_



In [65]:
df=pd.DataFrame(clf.cv_results_)
df


mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.000616      0.001231         0.001402        0.002804        1   
1       0.001615      0.003231         0.000226        0.000453        1   
2       0.001972      0.001880         0.000000        0.000000       20   
3       0.001128      0.002256         0.001629        0.001995       20   
4       0.001658      0.001547         0.000000        0.000000       50   
5       0.001990      0.003980         0.001602        0.003204       50   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
1          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
2       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 50, 'kernel': 'linear'}           1.000000   
5          rbf     {'C': 50, 'kernel': 'rbf'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.966667           0.966667                1.0   
2           1.000000           0.900000           0.933333                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.900000           0.933333                1.0   
5           0.966667           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.966667        0.042164                4  
3         0.966667        0.036515                3  
4         0.966667        0.042164                4  
5         0.960000        0.038873                6

In [66]:
df[['param_kernel','param_C','mean_test_score']]

param_kernel  param_C  mean_test_score
0       linear        1         0.980000
1          rbf        1         0.980000
2       linear       20         0.966667
3          rbf       20         0.966667
4       linear       50         0.966667
5          rbf       50         0.960000

In [67]:
clf.best_score_

0.9800000000000001

In [68]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}